// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from './application'

import HelloController from './hello_controller'
import StimulusReflex from 'stimulus_reflex'
import consumer from '../channels/consumer'
import controller from '../controllers/application_controller'
import CableReady from 'cable_ready'
application.register('hello', HelloController)
application.consumer = consumer
StimulusReflex.initialize(application, { controller, isolate: false })
CableReady.initialize({ consumer })
